export * from '@/infrastructure/database/drizzle/schemas/users';
export * from '@/infrastructure/database/drizzle/schemas/patients';
export * from '@/infrastructure/database/drizzle/schemas/doctors';
export * from '@/infrastructure/database/drizzle/schemas/specialties';
export * from '@/infrastructure/database/drizzle/schemas/health-plans';
export * from '@/infrastructure/database/drizzle/schemas/patient-health-plans';
export * from '@/infrastructure/database/drizzle/schemas/appointments';
export * from '@/infrastructure/database/drizzle/schemas/procedures';
export * from '@/infrastructure/database/drizzle/schemas/appointment-procedures';
